services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - database-net

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      VIRTUAL_HOST: ${PGADMIN_DOMAIN}
      LETSENCRYPT_HOST: ${PGADMIN_DOMAIN}
      LETSENCRYPT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    networks:
      - database-net
      - proxy-net

networks:
  database-net:
    external: true # red compartida con otros servicios de base de datos
  proxy-net:
    external: true # red compartida con nginx-proxy
